version: '3.8'
services:
  mysql_db:
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=caching_sha2_password
    environment:
      MYSQL_DATABASE: GalleryInsights
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      timeout: 20s
      retries: 10
    ports:
      - "3306:3306"
    container_name: mysql_db
    volumes:
      - db-data:/var/lib/mysql

  server:
    build: .
    container_name: server
    restart: always
    environment:
      DB: mysql_db
    ports:
      - "8888:8888"
    depends_on:
      mysql_db:
        condition: service_healthy
    links:
      - mysql_db

volumes:
  db-data:
    driver: local